x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.sonarr-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.sonarr-http.entrypoints: web
  traefik.http.routers.sonarr-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.sonarr-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.sonarr-https.entrypoints: websecure
  traefik.http.routers.sonarr-https.tls: true
  traefik.http.routers.sonarr-https.tls.certresolver: cloudflare
  traefik.http.routers.sonarr-https.service: ${APP_NAME}
  traefik.http.services.sonarr.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}
  homepage.widget.type: sonarr 
  homepage.widget.url: http://${APP_NAME}:${APP_PORT}
  homepage.widget.key: ${HOMEPAGE_WIDGET_KEY} 

x-kuma-labels: &kuma-template
  kuma.sonarr.http.name: ${HOMEPAGE_NAME}
  kuma.sonarr.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.sonarr.http.max_retries: 3
  kuma.sonarr.http.interval: 60



services:
  sonarr:
    container_name: ${APP_NAME}
    image: ghcr.io/hotio/sonarr:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./config:/config
      - /18tb/media:/data
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true