x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.qbittorrent-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.qbittorrent-http.entrypoints: web
  traefik.http.routers.qbittorrent-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.qbittorrent-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.qbittorrent-https.entrypoints: websecure
  traefik.http.routers.qbittorrent-https.tls: true
  traefik.http.routers.qbittorrent-https.tls.certresolver: cloudflare
  traefik.http.routers.qbittorrent-https.service: ${APP_NAME}
  traefik.http.services.qbittorrent.loadbalancer.server.port: ${APP_PORT}
  traefik.http.routers.copyparty-https.middlewares: authentik #proxy auth just in case

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}
  homepage.widget.type: qbittorrent
  homepage.widget.url: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.widget.username: ${HOMEPAGE_WIDGET_USERNAME}
  homepage.widget.password: ${HOMEPAGE_WIDGET_PASSWORD}

services:
  qbittorrent:
    container_name: ${APP_NAME}
    image: lscr.io/linuxserver/qbittorrent:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      PUID: "0"
      PGID: "0"
    ports:
      - 63531:63531
    volumes:
      - ./qbittorrent:/config
      - /18tb/media:/data
      - /18tb/kiwix/zim:/kiwix/zim
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true