x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.btop-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.btop-http.entrypoints: web
  traefik.http.routers.btop-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.btop-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.btop-https.entrypoints: websecure
  traefik.http.routers.btop-https.tls: true
  traefik.http.routers.btop-https.tls.certresolver: cloudflare
  traefik.http.routers.btop-https.service: ${APP_NAME}
  traefik.http.services.btop.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

services:
  btop:
    container_name: ${APP_NAME}
    image: bigbeartechworld/big-bear-btop:${IMAGE_TAG:-latest}
    restart: unless-stopped
    privileged: true
    cpuset: "5"
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - ./config:/root/.config/btop
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true