x-traefik-labels: &traefik-template
  traefik.enable: true
  # HTTP → HTTPS redirect
  traefik.http.routers.prowlarr-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.prowlarr-http.entrypoints: web
  traefik.http.routers.prowlarr-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  # HTTPS router
  traefik.http.routers.prowlarr-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.prowlarr-https.entrypoints: websecure
  traefik.http.routers.prowlarr-https.tls: true
  traefik.http.routers.prowlarr-https.tls.certresolver: cloudflare
  # Match router to a named service
  traefik.http.routers.prowlarr-https.service: prowlarr
  # Define internal port for the service
  traefik.http.services.prowlarr.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}
  #homepage.ping: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.widget.type: prowlarr 
  homepage.widget.url: https://prowlarr.pulosu.hexie.dev
  homepage.widget.key: ${HOMEPAGE_WIDGET_KEY}
  #homepage.widget.enableQueue: true  



services:
  prowlarr:
    container_name: ${APP_NAME}
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./prowlarr:/config
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true