x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.mealie-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.mealie-http.entrypoints: web
  traefik.http.routers.mealie-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.mealie-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.mealie-https.entrypoints: websecure
  traefik.http.routers.mealie-https.tls: true
  traefik.http.routers.mealie-https.tls.certresolver: cloudflare
  traefik.http.routers.mealie-https.service: ${APP_NAME}
  traefik.http.services.mealie.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

services:
  mealie:
    container_name: ${APP_NAME}
    image: hkotel/mealie:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      BASE_URL: https://${APP_NAME}.${BASE_DOMAIN}
      ALLOW_SIGNUP: "false"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_AUTH_STRATEGY: ${SMTP_SECURITY}
      SMTP_FROM_NAME: Mealie
      SMTP_FROM_EMAIL: ${SMTP_FROM}
      SMTP_USER: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - ./data:/app/data
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true