x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.ncdu-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.ncdu-http.entrypoints: web
  traefik.http.routers.ncdu-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.ncdu-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.ncdu-https.entrypoints: websecure
  traefik.http.routers.ncdu-https.tls: true
  traefik.http.routers.ncdu-https.tls.certresolver: cloudflare
  traefik.http.routers.ncdu-https.service: ${APP_NAME}
  traefik.http.services.ncdu.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.ncdu.http.name: ${HOMEPAGE_NAME}
  kuma.ncdu.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.ncdu.http.max_retries: 3
  kuma.ncdu.http.interval: 60

services:
  ncdu:
    container_name: ${APP_NAME}
    image: bigbeartechworld/big-bear-ncdu:${IMAGE_TAG:-latest}
    restart: unless-stopped
    privileged: true
    environment:
      NCDU_PATH: /w
    volumes:
      - /:/w:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true