x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.sonarr-anime-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.sonarr-anime-http.entrypoints: web
  traefik.http.routers.sonarr-anime-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.sonarr-anime-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.sonarr-anime-https.entrypoints: websecure
  traefik.http.routers.sonarr-anime-https.tls: true
  traefik.http.routers.sonarr-anime-https.tls.certresolver: cloudflare
  traefik.http.routers.sonarr-anime-https.service: ${APP_NAME}
  traefik.http.services.sonarr-anime.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}
  homepage.widget.type: sonarr 
  homepage.widget.url: https://sonarr-anime.pulosu.hexie.dev
  homepage.widget.key: ${HOMEPAGE_WIDGET_KEY}

x-kuma-labels: &kuma-template
  kuma.sonarr-anime.http.name: ${HOMEPAGE_NAME}
  kuma.sonarr-anime.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.sonarr-anime.http.max_retries: 3
  kuma.sonarr-anime.http.interval: 60

services:
  sonarr-anime:
    container_name: ${APP_NAME}
    image: ghcr.io/hotio/sonarr:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./config-anime:/config
      - /18tb/media:/data
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true