x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.wireguard-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.wireguard-http.entrypoints: web
  traefik.http.routers.wireguard-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.wireguard-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.wireguard-https.entrypoints: websecure
  traefik.http.routers.wireguard-https.tls: true
  traefik.http.routers.wireguard-https.tls.certresolver: cloudflare
  traefik.http.routers.wireguard-https.service: ${APP_NAME}
  traefik.http.services.wireguard.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.wireguard.http.name: ${HOMEPAGE_NAME}
  kuma.wireguard.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.wireguard.http.max_retries: 3
  kuma.wireguard.http.interval: 60

services:
  wireguard:
    container_name: ${APP_NAME}
    image: ghcr.io/wg-easy/wg-easy:${IMAGE_TAG:-15}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      DISABLE_IPV6: "true"
      WG_HOST: ${WG_HOST}
    ports:
      - 51820:51820/udp
    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true