x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.traefik-dashboard-http.rule: Host(`${APP_NAME}-dashboard.${BASE_DOMAIN}`)
  traefik.http.routers.traefik-dashboard-http.entrypoints: web
  traefik.http.routers.traefik-dashboard-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.traefik-dashboard-https.rule: Host(`${APP_NAME}-dashboard.${BASE_DOMAIN}`)
  traefik.http.routers.traefik-dashboard-https.entrypoints: websecure
  traefik.http.routers.traefik-dashboard-https.tls: true
  traefik.http.routers.traefik-dashboard-https.tls.certresolver: cloudflare
  traefik.http.routers.traefik-dashboard-https.service: api@internal

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}-dashboard.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}
  homepage.widget.type: traefik
  homepage.widget.url: https://${APP_NAME}-dashboard.${BASE_DOMAIN}
  homepage.widget.username: ${HOMEPAGE_WIDGET_USERNAME}
  homepage.widget.password: ${HOMEPAGE_WIDGET_PASSWORD}

services:
  traefik:
    container_name: ${APP_NAME}
    image: traefik:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./certs:/var/traefik/certs
    networks:
      - frontend
      - backend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true
  backend:
    external: true