x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.grafana-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.grafana-http.entrypoints: web
  traefik.http.routers.grafana-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.grafana-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.grafana-https.entrypoints: websecure
  traefik.http.routers.grafana-https.tls: true
  traefik.http.routers.grafana-https.tls.certresolver: cloudflare
  traefik.http.routers.grafana-https.service: ${APP_NAME}
  traefik.http.services.grafana.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

services:
  grafana:
    container_name: ${APP_NAME}
    image: grafana/grafana-enterprise:${IMAGE_TAG:-11.6.0}
    restart: unless-stopped
    user: "0:0"
    environment:
      GF_SERVER_ROOT_URL: https://${APP_NAME}.${BASE_DOMAIN}/
      GF_PLUGINS_PREINSTALL: grafana-clock-panel
    volumes:
      - ./grafana_storage:/var/lib/grafana
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true