x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.grafana-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.grafana-http.entrypoints: web
  traefik.http.routers.grafana-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.grafana-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.grafana-https.entrypoints: websecure
  traefik.http.routers.grafana-https.tls: true
  traefik.http.routers.grafana-https.tls.certresolver: cloudflare
  traefik.http.routers.grafana-https.service: ${APP_NAME}
  traefik.http.services.grafana.loadbalancer.server.port: ${APP_PORT}
  traefik.http.routers.grafana-https.middlewares: authentik #proxy auth just in case

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.grafana.http.name: ${HOMEPAGE_NAME}
  kuma.grafana.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.grafana.http.max_retries: 3
  kuma.grafana.http.interval: 60


services:
  grafana:
    container_name: ${APP_NAME}
    image: grafana/grafana-enterprise:${IMAGE_TAG:-11.6.0}
    restart: unless-stopped
    user: "0:0"
    environment:
      GF_SERVER_ROOT_URL: https://${APP_NAME}.${BASE_DOMAIN}/
      GF_PLUGINS_PREINSTALL: grafana-clock-panel
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: ${SMTP_HOST}:${SMTP_PORT}
      GF_SMTP_USER: ${SMTP_USERNAME}
      GF_SMTP_PASSWORD: ${SMTP_PASSWORD}
      GF_SMTP_FROM_ADDRESS: ${SMTP_FROM}
      GF_SMTP_STARTTLS_POLICY: ${SMTP_SECURITY}
    volumes:
      - ./grafana_storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - frontend
      - backend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true
  backend:
    external: true