x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.homepage-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.homepage-http.entrypoints: web
  traefik.http.routers.homepage-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.homepage-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.homepage-https.entrypoints: websecure
  traefik.http.routers.homepage-https.tls: true
  traefik.http.routers.homepage-https.tls.certresolver: cloudflare
  traefik.http.routers.homepage-https.service: ${APP_NAME}
  traefik.http.services.homepage.loadbalancer.server.port: ${APP_PORT}

x-kuma-labels: &kuma-template
  kuma.homepage.http.name: ${HOMEPAGE_NAME:-Homepage}
  kuma.homepage.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.homepage.http.max_retries: 3
  kuma.homepage.http.interval: 60

services:
  homepage:
    container_name: ${APP_NAME}
    image: ghcr.io/gethomepage/homepage:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${APP_NAME}.${BASE_DOMAIN}
      HOMEPAGE_VAR_PROXMOX_USERNAME: ${HOMEPAGE_VAR_PROXMOX_USERNAME}
      HOMEPAGE_VAR_PROXMOX_PASSWORD: ${HOMEPAGE_VAR_PROXMOX_PASSWORD}
    volumes:
      - .:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *kuma-template]

networks:
  frontend:
    external: true