x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.immich-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.immich-https.entrypoints: websecure
  traefik.http.routers.immich-https.tls: true
  traefik.http.routers.immich-https.tls.certresolver: cloudflare
  traefik.http.routers.immich-https.service: ${APP_NAME}
  traefik.http.services.immich.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.immich.http.name: ${HOMEPAGE_NAME}
  kuma.immich.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.immich.http.max_retries: 3
  kuma.immich.http.interval: 60

x-immich-env: &immich-env
  TZ: ${TZ:-Europe/Amsterdam}
  DB_HOSTNAME: immich-postgres
  DB_DATABASE_NAME: ${DB_DATABASE_NAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_USERNAME: ${DB_USERNAME}
  IMMICH_CONFIG_FILE: ${IMMICH_CONFIG_FILE}
  REDIS_HOSTNAME: immich-redis

services:
  immich-server:
    container_name: ${APP_NAME}
    image: altran1502/immich-server:${IMAGE_TAG:-release}
    restart: unless-stopped
    environment:
      <<: *immich-env
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "992"
    volumes:
      - ./config:/config
      - /18tb/immich/upload:/usr/src/app/upload
      - /18tb/Backup:/archive
      - /18tb/immich/data:/data
    networks:
      - frontend
      - backend
    depends_on:
      immich-postgres:
        condition: service_healthy
      immich-redis:
        condition: service_healthy
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

  immich-machine-learning:
    container_name: immich-machine-learning
    image: altran1502/immich-machine-learning:${IMAGE_TAG:-release}
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/Amsterdam}
    volumes:
      - /18tb/immich/model-cache:/cache
    networks:
      - backend

  immich-postgres:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/Amsterdam}
      POSTGRES_DB: immich-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --data-checksums
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname='immich-db' --username='${POSTGRES_USER}'"]
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 5m
      start_interval: 30s
    volumes:
      - /18tb/immich/pgdata:/var/lib/postgresql/data
    networks:
      - backend

  immich-redis:
    container_name: immich-redis
    image: redis:6.2-alpine
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/Amsterdam}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 20s
    volumes:
      - /18tb/immich/redis:/data
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true