x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.immich-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.immich-http.entrypoints: web
  traefik.http.routers.immich-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.immich-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.immich-https.entrypoints: websecure
  traefik.http.routers.immich-https.tls: true
  traefik.http.routers.immich-https.tls.certresolver: cloudflare
  traefik.http.routers.immich-https.service: ${APP_NAME}
  traefik.http.services.immich.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-immich-env: &immich-env
  DB_DATABASE_NAME: ${DB_DATABASE_NAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_USERNAME: ${DB_USERNAME}

services:
  immich-server:
    container_name: ${APP_NAME}
    image: altran1502/immich-server:${IMAGE_TAG:-v2.4.1}
    restart: unless-stopped
    environment:
      <<: *immich-env
    volumes:
      - ./config:/config
      - /18tb/immich/upload:/usr/src/app/upload
      - /18tb/Backup:/archive
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend
      - backend
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      <<: [*traefik-template, *homepage-template]

  immich-machine-learning:
    container_name: immich-machine-learning
    image: altran1502/immich-machine-learning:${IMAGE_TAG:-v2.4.1}
    restart: unless-stopped
    environment:
      <<: *immich-env
    volumes:
      - /18tb/immich/model-cache:/cache
    networks:
      - backend

  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: unless-stopped
    environment:
      POSTGRES_DB: immich-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --data-checksums
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname='immich-db' --username='${POSTGRES_USER}'"]
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 5m
      start_interval: 30s
    volumes:
      - /18tb/immich/pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: immich-redis
    image: redis:6.2-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 20s
    volumes:
      - /18tb/immich/redis:/data
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true