x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.thelounge-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.thelounge-http.entrypoints: web
  traefik.http.routers.thelounge-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.thelounge-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.thelounge-https.entrypoints: websecure
  traefik.http.routers.thelounge-https.tls: true
  traefik.http.routers.thelounge-https.tls.certresolver: cloudflare
  traefik.http.routers.thelounge-https.service: ${APP_NAME}
  traefik.http.services.thelounge.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.thelounge.http.name: ${HOMEPAGE_NAME}
  kuma.thelounge.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.thelounge.http.max_retries: 3
  kuma.thelounge.http.interval: 60



services:
  thelounge:
    container_name: ${APP_NAME}
    image: lscr.io/linuxserver/thelounge:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      - PUID=1000 
      - PGID=1000
    volumes:
      - ./config:/config
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true