x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.metubedl-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.metubedl-http.entrypoints: web
  traefik.http.routers.metubedl-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.metubedl-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.metubedl-https.entrypoints: websecure
  traefik.http.routers.metubedl-https.tls: true
  traefik.http.routers.metubedl-https.tls.certresolver: cloudflare
  traefik.http.routers.metubedl-https.service: ${APP_NAME}
  traefik.http.services.metubedl.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.metubedl.http.name: ${HOMEPAGE_NAME}
  kuma.metubedl.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.metubedl.http.max_retries: 3
  kuma.metubedl.http.interval: 60



services:
  metubedl:
    container_name: ${APP_NAME}
    image: alexta69/metube:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      - DEFAULT_THEME=dark
      - DELETE_FILE_ON_TRASHCAN=true
      - GID=1000
      - UID=1000
      - URL_PREFIX=/metube
    volumes:
      - ./downloads:/downloads
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true