x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.adguard-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.adguard-http.entrypoints: web
  traefik.http.routers.adguard-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.adguard-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.adguard-https.entrypoints: websecure
  traefik.http.routers.adguard-https.tls: true
  traefik.http.routers.adguard-https.tls.certresolver: cloudflare
  traefik.http.routers.adguard-https.service: ${APP_NAME}
  traefik.http.services.adguard.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.adguard.http.name: ${HOMEPAGE_NAME}
  kuma.adguard.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.adguard.http.max_retries: 3
  kuma.adguard.http.interval: 60

services:
  adguard:
    container_name: ${APP_NAME}
    image: adguard/adguardhome:${IMAGE_TAG:-v0.107.56}
    restart: unless-stopped
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./workdir:/opt/adguardhome/work
    ports:
      - 53:53/udp
      - 853:853/tcp
      - 784:784/udp
    networks:
      - frontend
      - backend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true
  backend:
    external: true