x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.${APP_NAME}-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.${APP_NAME}-http.entrypoints: web
  traefik.http.routers.${APP_NAME}-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.${APP_NAME}-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.${APP_NAME}-https.entrypoints: websecure
  traefik.http.routers.${APP_NAME}-https.tls: true
  traefik.http.routers.${APP_NAME}-https.tls.certresolver: cloudflare
  traefik.http.routers.${APP_NAME}-https.service: ${APP_NAME}
  traefik.http.services.${APP_NAME}.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}
  #homepage.ping: https://${APP_NAME}.${BASE_DOMAIN}



services:
  PLACEHOLDER:
    container_name: ${APP_NAME}
    image: PLACEHOLDER/ac:latest
    restart: unless-stopped
    user: "0:0"
    environment:
      - PUID=1000 
      - PGID=1000
    volumes:
      - ./config:/config
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true