x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.scrutiny-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.scrutiny-http.entrypoints: web
  traefik.http.routers.scrutiny-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.scrutiny-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.scrutiny-https.entrypoints: websecure
  traefik.http.routers.scrutiny-https.tls: true
  traefik.http.routers.scrutiny-https.tls.certresolver: cloudflare
  traefik.http.routers.scrutiny-https.service: ${APP_NAME}
  traefik.http.services.scrutiny.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.scrutiny.http.name: ${HOMEPAGE_NAME}
  kuma.scrutiny.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.scrutiny.http.max_retries: 3
  kuma.scrutiny.http.interval: 60

services:
  scrutiny:
    container_name: ${APP_NAME}
    image: ghcr.io/analogj/scrutiny:${IMAGE_TAG:-master-omnibus}
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    environment:
      COLLECTOR_CRON_SCHEDULE: "0 23 * * *"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
      - /etc/smart_drivedb.h:/etc/smart_drivedb.h:ro
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true