x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.crafty-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.crafty-http.entrypoints: web
  traefik.http.routers.crafty-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.crafty-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.crafty-https.entrypoints: websecure
  traefik.http.routers.crafty-https.tls: true
  traefik.http.routers.crafty-https.tls.certresolver: cloudflare
  traefik.http.routers.crafty-https.service: ${APP_NAME}
  traefik.http.services.crafty.loadbalancer.server.port: ${APP_PORT}
  traefik.http.services.crafty.loadbalancer.server.scheme: https

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

services:
  crafty:
    container_name: ${APP_NAME}
    image: registry.gitlab.com/crafty-controller/crafty-4:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      TZ: Etc/UTC
      USE_HTTPS: "false"
    ports:
      - 25565-25568:25565-25568
    volumes:
      - ./backups:/crafty/backups
      - ./logs:/crafty/logs
      - ./servers:/crafty/servers
      - ./config:/crafty/app/config
      - ./import:/crafty/import
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true