x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.glances-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.glances-http.entrypoints: web
  traefik.http.routers.glances-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.glances-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.glances-https.entrypoints: websecure
  traefik.http.routers.glances-https.tls: true
  traefik.http.routers.glances-https.tls.certresolver: cloudflare
  traefik.http.routers.glances-https.service: ${APP_NAME}
  traefik.http.services.glances.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.glances.http.name: ${HOMEPAGE_NAME}
  kuma.glances.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.glances.http.max_retries: 3
  kuma.glances.http.interval: 60

services:
  glances:
    container_name: ${APP_NAME}
    image: nicolargo/glances:${IMAGE_TAG:-ubuntu-latest-full}
    restart: unless-stopped
    pid: host
    environment:
      GLANCES_OPT: -w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /etc/os-release:/etc/os-release:ro
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true