x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.bazarr-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.bazarr-http.entrypoints: web
  traefik.http.routers.bazarr-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.bazarr-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.bazarr-https.entrypoints: websecure
  traefik.http.routers.bazarr-https.tls: true
  traefik.http.routers.bazarr-https.tls.certresolver: cloudflare
  traefik.http.routers.bazarr-https.service: ${APP_NAME}
  traefik.http.services.bazarr.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}
  homepage.widget.type: bazarr
  homepage.widget.url: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.widget.key: ${HOMEPAGE_WIDGET_KEY}

x-kuma-labels: &kuma-template
  kuma.bazarr.http.name: ${HOMEPAGE_NAME}
  kuma.bazarr.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.bazarr.http.max_retries: 3
  kuma.bazarr.http.interval: 60

services:
  bazarr:
    container_name: ${APP_NAME}
    image: lscr.io/linuxserver/bazarr:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      PUID: "0"
      PGID: "0"
    volumes:
      - ./config:/config
      - /18tb/media:/data
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]

networks:
  frontend:
    external: true