x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.uptime-kuma-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.uptime-kuma-http.entrypoints: web
  traefik.http.routers.uptime-kuma-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.uptime-kuma-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.uptime-kuma-https.entrypoints: websecure
  traefik.http.routers.uptime-kuma-https.tls: true
  traefik.http.routers.uptime-kuma-https.tls.certresolver: cloudflare
  traefik.http.routers.uptime-kuma-https.service: ${APP_NAME}
  traefik.http.services.uptime-kuma.loadbalancer.server.port: ${APP_PORT}

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

x-kuma-labels: &kuma-template
  kuma.uptime-kuma.http.name: ${HOMEPAGE_NAME}
  kuma.uptime-kuma.http.url: https://${APP_NAME}.${BASE_DOMAIN}
  kuma.uptime-kuma.http.max_retries: 3
  kuma.uptime-kuma.http.interval: 60

services:
  uptime-kuma:
    container_name: ${APP_NAME}
    image: louislam/uptime-kuma:${IMAGE_TAG:-1}
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template, *kuma-template]
  autokuma:
    container_name: autokuma
    image: ghcr.io/bigboot/autokuma:${AUTOKUMA_TAG:-latest}
    restart: unless-stopped
    environment:
      AUTOKUMA__KUMA__URL: http://uptime-kuma:3001
      AUTOKUMA__KUMA__USERNAME: ${KUMA_USERNAME}
      AUTOKUMA__KUMA__PASSWORD: ${KUMA_PASSWORD}
      AUTOKUMA__TAG_NAME: auto
      AUTOKUMA__DEFAULT_SETTINGS: |-
        docker.docker_container: ""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend

networks:
  frontend:
    external: true