x-traefik-labels: &traefik-template
  traefik.enable: true
  traefik.http.routers.copyparty-http.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.copyparty-http.entrypoints: web
  traefik.http.routers.copyparty-http.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  traefik.http.routers.copyparty-https.rule: Host(`${APP_NAME}.${BASE_DOMAIN}`)
  traefik.http.routers.copyparty-https.entrypoints: websecure
  traefik.http.routers.copyparty-https.tls: true
  traefik.http.routers.copyparty-https.tls.certresolver: cloudflare
  traefik.http.routers.copyparty-https.service: ${APP_NAME}
  traefik.http.services.copyparty.loadbalancer.server.port: ${APP_PORT}
  traefik.http.routers.copyparty-https.middlewares: authentik #proxy auth just in case

x-homepage-labels: &homepage-template
  homepage.group: ${HOMEPAGE_GROUP}
  homepage.name: ${HOMEPAGE_NAME}
  homepage.icon: ${HOMEPAGE_ICON}
  homepage.href: https://${APP_NAME}.${BASE_DOMAIN}
  homepage.description: ${HOMEPAGE_DESCRIPTION}

services:
  copyparty:
    container_name: ${APP_NAME}
    image: copyparty/ac:${IMAGE_TAG:-latest}
    restart: unless-stopped
    user: "0:0"
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.2
      PYTHONUNBUFFERED: 1
    stop_grace_period: 15s
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
    volumes:
      - /apps/copyparty:/cfg:z
      - /18tb/Backup:/18tb:z
      - /apps:/apps:z
    networks:
      - frontend
    labels:
      <<: [*traefik-template, *homepage-template]

networks:
  frontend:
    external: true