services:
  botty:
    image: ghcr.io/hexiejexie/botty-discord:latest
    container_name: botty
    restart: unless-stopped
    env_file:
      - .env
    # Build from the local Dockerfile when running `docker compose up --build` for testing.
    #build:
    #  context: .
    #  dockerfile: Dockerfile