services:
  discord-bot:
    container_name: ${APP_NAME}
    image: hexiejexie/discord-ip-bot:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      COMMAND: "!showip"
    volumes:
      - ./data:/app/data