services:
  crowdsec:
    container_name: ${APP_NAME}
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped
    environment:
      - GID=1000
    volumes:
      - ./config:/etc/crowdsec
      - /18tb/crowdsec/data:/var/lib/crowdsec/data
      - /var/log:/var/log:ro
    networks:
      - frontend

networks:
  frontend:
    external: true